if (NOT DEFINED CPACK_GENERATOR)
  sonar_cpack_generator(CPACK_GENERATOR)
endif()

if (NOT DEFINED CPACK_PACKAGING_INSTALL_PREFIX)
  set(CPACK_PACKAGING_INSTALL_PREFIX "/")
endif()

if (NOT DEFINED CPACK_PACKAGE_VERSION_MAJOR)
  sonar_cpack_version(CPACK_PACKAGE_VERSION_MAJOR
    CPACK_PACKAGE_VERSION_MINOR
    CPACK_PACKAGE_VERSION_PATCH)
endif()

set(CPACK_SET_DESTDIR true)
set(CPACK_PACKAGE_VENDOR "jsonar")
set(CPACK_PACKAGE_CONTACT "jSonar Support <support@jsonar.com>")

if (${CPACK_GENERATOR} STREQUAL "RPM")
  execute_process(COMMAND uname "-m"
    OUTPUT_VARIABLE CPACK_RPM_PACKAGE_ARCHITECTURE
    OUTPUT_STRIP_TRAILING_WHITESPACE)
  execute_process(
    COMMAND rpm "-q" "--queryformat" "%{RELEASE}" rpm
    COMMAND rev
    COMMAND cut "-d." "-f1"
    COMMAND rev
    OUTPUT_VARIABLE RHEL
    OUTPUT_STRIP_TRAILING_WHITESPACE)

  set (CPACK_PACKAGE_FILE_NAME
    "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}${CPACK_PACKAGE_VERSION_EXTRA}.${RHEL}.${CPACK_PACKAGE_VENDOR}.${CPACK_RPM_PACKAGE_ARCHITECTURE}")

  list(APPEND CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION
    "${CPACK_PACKAGING_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/pkgconfig")
  SET(CPACK_RPM_PACKAGE_LICENSE "2016 jSonar Inc")
  SET(CPACK_RPM_PACKAGE_GROUP "Applications/Databases")
  SET(CPACK_RPM_PACKAGE_URL "http://www.jsonar.com/")
  SET(CPACK_RPM_PACKAGE_DESCRIPTION ${CPACK_PACKAGE_DESCRIPTION})
elseif(${CPACK_GENERATOR} STREQUAL "DEB")
  set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
  set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
endif()

include(CPack)
